name: "Bump Version"
# include major/minor/patch in commit message
# Pull after publishing release/ branch
on:
  push:
    branches:
      - "release/**"

jobs:
  bump-version:
    name: "Bump Version on release branch"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}

      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.github_token }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          add: '*.md'

      - name: "cat package.json"
        run: cat ./package.json
      - name: "Setup Node.js"
        uses: "actions/setup-node@v2.2.0"
        with:
          node-version: 12
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: 'pre-'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "cat package.json"
        run: cat ./package.json